server:
  port: ${crawler.master-port}

spring:
  http:
    encoding:
      force: true
  rabbitmq:
    addresses: ${crawler.rabbit-uri}
  data:
    mongodb:
      uri: ${crawler.mongo-db-uri}
      repositories:
        type: imperative
